# Generated by Django 4.1.3 on 2022-12-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userauthcodes"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userauthcodes",
            managers=[],
        ),
    ]
