# Generated by Django 4.1.3 on 2022-12-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_userauthcodes_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(auto_now_add=True),
        ),
    ]
