# Generated by Django 4.1.3 on 2022-12-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_userauthcodes_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userauthcodes",
            name="expires_at",
            field=models.DateTimeField(),
        ),
    ]
