# Generated by Django 4.1.3 on 2022-12-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_userauthcodes_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bvn",
        ),
        migrations.AddField(
            model_name="profile",
            name="credit_limit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
