# Generated by Django 4.1.3 on 2022-12-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_profile_pin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="verified",
        ),
    ]
