# Generated by Django 4.1.3 on 2022-12-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_remove_profile_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
