# Generated by Django 4.1.3 on 2023-02-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_profile_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pin",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ref_code",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
