# Generated by Django 4.1.3 on 2023-06-09 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0014_alter_profile_dob_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.CreateModel(
            name='OkraLinkedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('registered_bank_id', models.CharField(max_length=100)),
                ('registered_record', models.CharField(max_length=100)),
                ('income_accounts', models.CharField(max_length=1000)),
                ('income_banks', models.CharField(max_length=1000)),
                ('avg_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('initial_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
