# Generated by Django 4.1.3 on 2023-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_profile_credit_limit_okralinkeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_active_loan',
            field=models.BooleanField(default=False),
        ),
    ]
