# Generated by Django 4.1.3 on 2023-07-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_credit_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okralinkeduser',
            name='income_accounts',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
