# Generated by Django 4.1.3 on 2023-07-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_okralinkeduser_income_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='okralinkeduser',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
