# Generated by Django 4.1.3 on 2023-07-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_okralinkeduser_monthly_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='okralinkeduser',
            old_name='monthly_salary',
            new_name='avg_monthly_salary',
        ),
    ]
