# Generated by Django 4.1.3 on 2023-08-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0021_remove_okralinkeduser_avg_monthly_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userauthcodes",
            name="checker",
            field=models.CharField(blank=True, default="1", max_length=1),
        ),
    ]
