# Generated by Django 4.1.3 on 2023-08-25 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0022_userauthcodes_checker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userauthcodes",
            name="checker",
        ),
    ]
