# Generated by Django 4.1.3 on 2023-08-30 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0023_remove_userauthcodes_checker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="okralinkeduser",
            name="registered_bank_id",
        ),
    ]
