# Generated by Django 4.1.3 on 2023-09-30 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0030_alter_profile_pin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="pin",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="security_answer_1",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="security_answer_2",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="security_question_1",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="security_question_2",
        ),
        migrations.CreateModel(
            name="SensitiveData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_pin_hash", models.CharField(max_length=128)),
                ("security_question_hash", models.CharField(max_length=128)),
                ("security_answer_hash", models.CharField(max_length=128)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
