# Generated by Django 4.1.3 on 2023-09-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0031_remove_profile_pin_remove_profile_security_answer_1_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensitivedata",
            old_name="security_answer_hash",
            new_name="security_answer_1_hash",
        ),
        migrations.RenameField(
            model_name="sensitivedata",
            old_name="security_question_hash",
            new_name="security_answer_2_hash",
        ),
        migrations.AddField(
            model_name="sensitivedata",
            name="security_answer_3_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="sensitivedata",
            name="security_question_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="q1",
                to="account.securityquestion",
            ),
        ),
        migrations.AddField(
            model_name="sensitivedata",
            name="security_question_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="q2",
                to="account.securityquestion",
            ),
        ),
        migrations.AddField(
            model_name="sensitivedata",
            name="security_question_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="q3",
                to="account.securityquestion",
            ),
        ),
        migrations.AlterField(
            model_name="sensitivedata",
            name="transaction_pin_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
