# Generated by Django 4.1.3 on 2023-10-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0032_rename_security_answer_hash_sensitivedata_security_answer_1_hash_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pin_set",
            field=models.BooleanField(default=False),
        ),
    ]
