# Generated by Django 4.1.3 on 2022-12-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_service_deposit_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="decription",
            field=models.CharField(default="Demo", max_length=100),
        ),
    ]
