# Generated by Django 4.1.3 on 2022-12-29 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_service_decription"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="amount_to_pay_back",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_transaction",
                to="core.loan",
            ),
        ),
    ]
