# Generated by Django 4.1.3 on 2022-12-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_loan_amount_to_pay_back_transaction_loan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("FR", "Fee Repayment"), ("WT", "Wallet Top Up")],
                default="WT",
                max_length=3,
            ),
        ),
    ]
