# Generated by Django 4.1.3 on 2022-12-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("LO", "Loan"),
                    ("FR", "Fee Repayment"),
                    ("WT", "Wallet Top Up"),
                ],
                default="WT",
                max_length=3,
            ),
        ),
    ]
