# Generated by Django 4.1.3 on 2023-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_decription_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("FR", "Fee Repayment"), ("WT", "Wallet Top Up")],
                default="WT",
                max_length=3,
            ),
        ),
    ]
