# Generated by Django 4.1.3 on 2023-04-18 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
