# Generated by Django 4.1.3 on 2023-07-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_schoolbank_remove_loan_down_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('succeeded', 'Succeeded')], default='pending', max_length=20),
        ),
    ]
