# Generated by Django 4.1.3 on 2023-07-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_paymentslip_reference_alter_paymentslip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='api_reference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
