# Generated by Django 4.1.3 on 2023-07-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transaction_api_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='api_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
