# Generated by Django 4.1.3 on 2023-07-15 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_transaction_api_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 15, 18, 2, 42, 529411, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
