# Generated by Django 4.1.3 on 2023-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_loan_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='receivers_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
