# Generated by Django 4.1.3 on 2023-09-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_paymentslip_receivers_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("FR", "Fee Repayment"),
                    ("SFP", "Fees Paid"),
                    ("LN", "Wallet Top Up"),
                ],
                default="WT",
                max_length=3,
            ),
        ),
    ]
