# Generated by Django 4.1.3 on 2023-09-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentslip",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_payment_slip",
                to="core.loan",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_slip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_slip",
                to="core.paymentslip",
            ),
        ),
    ]
