# Generated by Django 4.1.3 on 2023-09-14 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_paymentslip_loan_transaction_payment_slip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentslip",
            name="loan",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="payment_slip",
        ),
    ]
