# Generated by Django 4.1.3 on 2023-09-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_remove_paymentslip_loan_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentslip",
            old_name="receivers_name",
            new_name="recipient",
        ),
        migrations.AddField(
            model_name="paymentslip",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="schoolbank",
            name="address",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
